POST http://localhost:3000/employees HTTP/1.1
Content-Type: application/json

{  
    "firstName": "TESTE1",
    "lastName": "Antunes2",
    "email": "anna@antunes.com",
    "phoneNumber": "123-456-7890",
    "birthday": "08/27/1998",
    "jobPosition": "frontend developer",
    "salary": "9000"
}


###
PUT http://localhost:3000/employees/652a9b1a605914763cc7565d HTTP/1.1
Content-Type: application/json

{
    "firstName": "TESTE23",
    "lastName": "Antunes1",
    "email": "anna@antunes1.com",
    "phoneNumber": "123-456-7890",
    "birthday": "08/27/1998",
    "jobPosition": "frontend developer",
    "salary": "8000"
}

###
GET http://localhost:3000/employees

###
GET http://localhost:3000/auth/logout

###
GET http://localhost:3000/employees/652a9b1a605914763cc7565d
###
DELETE http://localhost:3000/employees/653be7ea93d33478ad62560e

###
POST http://localhost:3000/auth/create HTTP/1.1
Content-Type: application/json

{  
    "username": "Marcos Antunes",
    "email": "test1@test1.com",
    "password": "blablablatest"
}

###
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{  
    "email": "test1@test1.com",
    "password": "blablablatest"
}

###
PUT http://localhost:3000/auth/update/65454466707c6b846a4aa77c HTTP/1.1
Content-Type: application/json

{  
    "username": "test",
    "email": "marcos@antunes.com" 
}

###
GET http://localhost:3000/auth/logout


###
GET https://cse341project2-bkgg.onrender.com/employees

###
GET https://cse341project2-bkgg.onrender.com/employees/652a9b1a605914763cc7565d

###
POST https://cse341project2-bkgg.onrender.com/employees HTTP/1.1
Content-Type: application/json

{
    "firstName": "Rafael",
    "lastName": "Antunes",
    "email": "rafael@antunes.com",
    "phoneNumber": "123-123-7890",
    "birthday": "05/27/2000",
    "jobPosition": "frontend developer",
    "salary": "5000"
}

